// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_reels/test/unit/core/services/button_events_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_reels/core/platform/messages.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FlutterReelsButtonEventsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterReelsButtonEventsApi extends _i1.Mock
    implements _i2.FlutterReelsButtonEventsApi {
  MockFlutterReelsButtonEventsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onBeforeLikeButtonClick(String? videoId) => super.noSuchMethod(
        Invocation.method(
          #onBeforeLikeButtonClick,
          [videoId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAfterLikeButtonClick(
    String? videoId,
    bool? isLiked,
    int? likeCount,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onAfterLikeButtonClick,
          [
            videoId,
            isLiked,
            likeCount,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onShareButtonClick(_i2.ShareData? shareData) => super.noSuchMethod(
        Invocation.method(
          #onShareButtonClick,
          [shareData],
        ),
        returnValueForMissingStub: null,
      );
}
