# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Flutter module Add-to-App setup
flutter_application_path = '../../reels_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ReelsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Native iOS SDK (wraps Flutter)
  pod 'ReelsIOS', :path => '../../reels_ios'
  
  # Install Flutter and plugins (Add-to-App)
  install_all_flutter_pods(flutter_application_path)

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
