name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: flutter_reels
        run: flutter pub get

      - name: Build Android AAR
        working-directory: flutter_reels
        run: flutter build aar --release

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Maven repository structure
        run: |
          mkdir -p maven-repo/com/github/eishon/flutter-reels/${{ steps.get_version.outputs.VERSION }}
          
          # Copy AAR files
          find flutter_reels/build/host/outputs/repo -name "*.aar" -exec cp {} maven-repo/com/github/eishon/flutter-reels/${{ steps.get_version.outputs.VERSION }}/ \;
          
          # Create POM file
          cat > maven-repo/com/github/eishon/flutter-reels/${{ steps.get_version.outputs.VERSION }}/flutter-reels-${{ steps.get_version.outputs.VERSION }}.pom << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.github.eishon</groupId>
            <artifactId>flutter-reels</artifactId>
            <version>${{ steps.get_version.outputs.VERSION }}</version>
            <packaging>aar</packaging>
            <name>Flutter Reels</name>
            <description>A Flutter module for displaying reels/stories that can be integrated into native Android and iOS apps</description>
            <url>https://github.com/eishon/flutter-reels</url>
            <licenses>
              <license>
                <name>MIT License</name>
                <url>https://github.com/eishon/flutter-reels/blob/master/LICENSE</url>
              </license>
            </licenses>
          </project>
          EOF

      - name: Publish to GitHub Packages
        run: |
          cd maven-repo
          for file in $(find . -type f); do
            dir=$(dirname $file)
            filename=$(basename $file)
            curl -X PUT \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @$file \
              "https://maven.pkg.github.com/eishon/flutter-reels/${dir}/${filename}"
          done

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          cp -r maven-repo artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-repository
          path: artifacts/
