name: Publish iOS CocoaPod

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-ios-pod:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: flutter_reels
        run: flutter pub get

      - name: Build iOS Framework
        working-directory: flutter_reels
        run: flutter build ios-framework --release

      - name: Get version from tag
        id: get_version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "VERSION=snapshot" >> $GITHUB_OUTPUT
          fi

      - name: Update podspec version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          sed -i '' "s/s.version.*=.*/s.version = '$VERSION'/" FlutterReels.podspec

      - name: Create CocoaPods Specs Repository Structure
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          
          # Create specs directory structure
          mkdir -p cocoapods-specs/FlutterReels/$VERSION
          
          # Copy podspec
          cp FlutterReels.podspec cocoapods-specs/FlutterReels/$VERSION/
          
          # Create frameworks archive for the podspec
          mkdir -p Frameworks
          cp -R flutter_reels/build/ios/framework/Release/*.xcframework Frameworks/
          
          # Create a zip file for frameworks
          zip -r flutter_reels-ios-frameworks.zip Frameworks/
          
          # Create Classes directory (required by CocoaPods)
          mkdir -p FlutterReels/Classes
          touch FlutterReels/Classes/.gitkeep

      - name: Validate podspec
        run: |
          # Skip validation for now as it requires the release to be published first
          echo "Podspec will be validated after release is published"

      - name: Checkout cocoapods-specs branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create or checkout cocoapods-specs branch
          git checkout -b cocoapods-specs 2>/dev/null || git checkout cocoapods-specs || git checkout --orphan cocoapods-specs
          
          # Remove all files except .git
          git rm -rf . 2>/dev/null || true
          
          # Copy specs repository
          cp -r cocoapods-specs/* . 2>/dev/null || true
          
          # Add and commit
          git add .
          git commit -m "Publish FlutterReels podspec v${{ steps.get_version.outputs.VERSION }}" || echo "No changes to commit"
          
          # Push to cocoapods-specs branch
          git push origin cocoapods-specs --force

      - name: Create Podspec README
        run: |
          git checkout cocoapods-specs
          
          cat > README.md << 'EOF'
          # Flutter Reels CocoaPods Specs Repository
          
          This branch contains the CocoaPods podspecs for Flutter Reels.
          
          ## Usage
          
          Add this to your `Podfile`:
          
          ```ruby
          source 'https://github.com/eishon/flutter-reels.git'
          source 'https://cdn.cocoapods.org/'
          
          target 'YourApp' do
            use_frameworks!
            
            # Flutter Reels module
            pod 'FlutterReels', '~> ${{ steps.get_version.outputs.VERSION }}'
          end
          ```
          
          Then run:
          
          ```bash
          pod install
          ```
          
          For more information, visit: https://github.com/eishon/flutter-reels
          EOF
          
          git add README.md
          git commit -m "Update README" || echo "No changes"
          git push origin cocoapods-specs

      - name: Upload podspec artifact
        uses: actions/upload-artifact@v4
        with:
          name: podspec
          path: FlutterReels.podspec
