name: Publish AAR to Repository

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-aar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: flutter_reels
        run: flutter pub get

      - name: Build Android AAR
        working-directory: flutter_reels
        run: flutter build aar --release

      - name: Get version from tag
        id: get_version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=snapshot" >> $GITHUB_OUTPUT
          fi

      - name: Create Maven repository structure
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          
          # Create directory structure
          mkdir -p maven/com/github/eishon/flutter_reels/$VERSION
          
          # Find and copy the release AAR
          RELEASE_AAR=$(find flutter_reels/build/host/outputs/repo -name "*release*.aar" | head -n 1)
          
          if [ -n "$RELEASE_AAR" ]; then
            cp "$RELEASE_AAR" maven/com/github/eishon/flutter_reels/$VERSION/flutter_reels-$VERSION.aar
            
            # Create POM file
            cat > maven/com/github/eishon/flutter_reels/$VERSION/flutter_reels-$VERSION.pom << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                                       http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            
            <groupId>com.github.eishon</groupId>
            <artifactId>flutter_reels</artifactId>
            <version>$VERSION</version>
            <packaging>aar</packaging>
            
            <name>Flutter Reels</name>
            <description>A Flutter module for displaying reels/stories that can be integrated into native Android and iOS apps</description>
            <url>https://github.com/eishon/flutter-reels</url>
            
            <licenses>
              <license>
                <name>MIT License</name>
                <url>https://github.com/eishon/flutter-reels/blob/master/LICENSE</url>
                <distribution>repo</distribution>
              </license>
            </licenses>
            
            <scm>
              <url>https://github.com/eishon/flutter-reels</url>
              <connection>scm:git:git://github.com/eishon/flutter-reels.git</connection>
              <developerConnection>scm:git:ssh://git@github.com/eishon/flutter-reels.git</developerConnection>
            </scm>
            
            <dependencies>
              <dependency>
                <groupId>io.flutter</groupId>
                <artifactId>flutter_embedding_release</artifactId>
                <version>1.0.0-0fdb562ac8069a8b4e3c9344b6d3dcff8961e6d9</version>
                <type>aar</type>
              </dependency>
            </dependencies>
          </project>
          EOF
            
            # Create maven-metadata.xml
            cat > maven/com/github/eishon/flutter_reels/maven-metadata.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <metadata>
            <groupId>com.github.eishon</groupId>
            <artifactId>flutter_reels</artifactId>
            <versioning>
              <latest>$VERSION</latest>
              <release>$VERSION</release>
              <versions>
                <version>$VERSION</version>
              </versions>
              <lastUpdated>$(date +%Y%m%d%H%M%S)</lastUpdated>
            </versioning>
          </metadata>
          EOF
          fi

      - name: Checkout releases branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create or checkout releases branch
          git checkout -b releases 2>/dev/null || git checkout releases || git checkout --orphan releases
          
          # Remove all files except .git
          git rm -rf . 2>/dev/null || true
          
          # Copy maven repository
          cp -r maven/* .
          
          # Add and commit
          git add .
          git commit -m "Publish AAR v${{ steps.get_version.outputs.VERSION }}" || echo "No changes to commit"
          
          # Push to releases branch
          git push origin releases --force

      - name: Create README for releases branch
        run: |
          cat > README.md << 'EOF'
          # Flutter Reels - Maven Repository
          
          This branch contains the Maven repository for Flutter Reels AAR packages.
          
          ## Usage
          
          Add this to your `settings.gradle`:
          
          ```gradle
          dependencyResolutionManagement {
              repositories {
                  maven {
                      url = uri("https://raw.githubusercontent.com/eishon/flutter-reels/releases/")
                  }
              }
          }
          ```
          
          Add the dependency in your `app/build.gradle`:
          
          ```gradle
          dependencies {
              implementation 'com.github.eishon:flutter_reels:${{ steps.get_version.outputs.VERSION }}'
          }
          ```
          
          For more information, visit: https://github.com/eishon/flutter-reels
          EOF
          
          git add README.md
          git commit -m "Update README" || echo "No changes"
          git push origin releases
