name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: flutter_reels
        run: flutter pub get

      - name: Build Android AAR
        working-directory: flutter_reels
        run: flutter build aar --release

      - name: Create artifacts directory
        run: mkdir -p artifacts/android

      - name: Copy AAR files
        run: |
          find flutter_reels/build/host/outputs -name "*.aar" -exec cp {} artifacts/android/ \;
          
      - name: Create Android archive
        run: |
          cd artifacts/android
          zip -r flutter_reels-android.zip *.aar
          cd ../..

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: artifacts/android/flutter_reels-android.zip

  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: flutter_reels
        run: flutter pub get

      - name: Build iOS Framework
        working-directory: flutter_reels
        run: flutter build ios-framework --release

      - name: Create artifacts directory
        run: mkdir -p artifacts/ios

      - name: Copy iOS frameworks
        run: |
          cp -R flutter_reels/build/ios/framework/Release/* artifacts/ios/

      - name: Create iOS archive
        run: |
          cd artifacts/ios
          zip -r flutter_reels-ios.zip .
          cd ../..

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: artifacts/ios/flutter_reels-ios.zip

  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release
          path: ./artifacts

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-release
          path: ./artifacts

      - name: Get tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release Notes
        run: |
          echo "# Flutter Reels ${{ steps.tag_name.outputs.TAG }}" > release-notes.md
          echo "" >> release-notes.md
          echo "## What's Included" >> release-notes.md
          echo "" >> release-notes.md
          echo "- **flutter_reels-android.zip**: Android AAR files for integration" >> release-notes.md
          echo "- **flutter_reels-ios.zip**: iOS frameworks (Flutter.xcframework and App.xcframework)" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Integration Instructions" >> release-notes.md
          echo "" >> release-notes.md
          echo "Please refer to the [README.md](https://github.com/${{ github.repository }}/blob/${{ steps.tag_name.outputs.TAG }}/flutter_reels/README.md) for detailed integration instructions." >> release-notes.md
          echo "" >> release-notes.md
          echo "## Build Information" >> release-notes.md
          echo "" >> release-notes.md
          echo "- **Flutter Version**: 3.16.5" >> release-notes.md
          echo "- **Build Date**: $(date)" >> release-notes.md
          echo "- **Commit**: ${{ github.sha }}" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Platform Requirements" >> release-notes.md
          echo "" >> release-notes.md
          echo "### Android" >> release-notes.md
          echo "- Minimum SDK: 21 (Android 5.0)" >> release-notes.md
          echo "- Target SDK: 33" >> release-notes.md
          echo "- Gradle: 7.0+" >> release-notes.md
          echo "" >> release-notes.md
          echo "### iOS" >> release-notes.md
          echo "- Minimum iOS: 12.0" >> release-notes.md
          echo "- Xcode: 14.0+" >> release-notes.md
          echo "- CocoaPods: 1.10+" >> release-notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/flutter_reels-android.zip
            artifacts/flutter_reels-ios.zip
          body_path: release-notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
